name: Run the full Test Suite
on:
  workflow_dispatch:
    inputs:
      show-output:
        description: 'Whether to include logs as users see them in tracebacks.'
        required: false
        default: false

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker build -t oi --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} .
      - name: Installing Pip Dependencies
        run: |
          cd utility
          pip install -r requirements.txt
      - name: Pytest
        run: |
          pytest utility/tests [ ${{ inputs }} = true ] && echo "-v" || echo ""
